name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # This runs the action daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hitarthsh
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg
