name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generate the snake animation SVG files
      - uses: Platane/snk@v3
        id: snake-svg
        with:
          github_user_name: hitarthsh
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit and push files to GitHub main branch
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: '🐍 Generate Snake Animation'
          add: 'dist'
          push: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
